#
# This is free software, license use GPLv3.
#
# Copyright (c) 2020, Chuck <fanck0605@qq.com>
#

name: openwrt-21.02

on:
  push:
    branches: [ openwrt-21.02 ]
  pull_request:
    branches: [ openwrt-21.02 ]

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Set timezone
        uses: szenius/set-timezone@v1.1
        with:
          timezoneLinux: "Asia/Shanghai"
          timezoneMacos: "Asia/Shanghai"
          timezoneWindows: "China Standard Time"

      - name: Checkout Project
        uses: actions/checkout@v3
        with:
          ref: openwrt-21.02

      - name: Show large directories
        run: |
          df -h
          sudo du -xh --exclude=/{proc,sys,dev} / | grep -E '^[0-9.]*?[GTPEZY]'

      - name: Initialize Environment
        env:
          DEBIAN_FRONTEND: noninteractive
        run: |
          sudo rm -rf /usr/local/lib/android
          sudo apt-get update
          sudo apt-get install build-essential ccache ecj fastjar file g++ gawk gettext git java-propose-classpath libelf-dev libncurses5-dev libncursesw5-dev libssl-dev python python2.7-dev python3 unzip wget python-distutils-extra python3-setuptools python3-dev quilt rsync subversion swig time xsltproc zlib1g-dev 
          sudo apt-get autoremove --purge
          sudo apt-get clean
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Show disk space usage
        run: |
          df -h

      - name: Build OpenWrt
        run: |
          ./build.sh

      - name: Assemble Artifact
        id: assemble_artifact
        run: |
          echo "artifact_name=OpenWrt_$(date +%Y%m%d)_NanoPi-R2S" >>"$GITHUB_OUTPUT"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ steps.assemble_artifact.outputs.artifact_name }}
          path: artifact
